# Generated by Django 4.2.18 on 2025-08-08 08:38

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):
    dependencies = [
        ("structuretimers", "0006_add_theft_timer_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationrule",
            name="exclude_structure_types",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ("35832", "Astrahus"),
                    ("35833", "Fortizar"),
                    ("47512", "'Moreau' Fortizar"),
                    ("47513", "'Draccous' Fortizar"),
                    ("47514", "'Horizon' Fortizar"),
                    ("47515", "'Marginis' Fortizar"),
                    ("47516", "'Prometheus' Fortizar"),
                    ("35834", "Keepstar"),
                    ("40340", "Upwell Palatine Keepstar"),
                    ("35835", "Athanor"),
                    ("35836", "Tatara"),
                    ("35825", "Raitaru"),
                    ("35826", "Azbel"),
                    ("35827", "Sotiyo"),
                    ("35841", "Ansiblex Jump Bridge"),
                    ("35840", "Pharolux Cyno Beacon"),
                    ("37534", "Tenebrex Cyno Jammer"),
                    ("4736", "Orbital Skyhook"),
                    ("81826", "Metenox Moon Drill"),
                    ("32458", "Sovereignty Hub"),
                ],
                help_text="Structure type must NOT be one of the selected",
                max_length=118,
            ),
        ),
        migrations.AddField(
            model_name="notificationrule",
            name="require_structure_types",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ("35832", "Astrahus"),
                    ("35833", "Fortizar"),
                    ("47512", "'Moreau' Fortizar"),
                    ("47513", "'Draccous' Fortizar"),
                    ("47514", "'Horizon' Fortizar"),
                    ("47515", "'Marginis' Fortizar"),
                    ("47516", "'Prometheus' Fortizar"),
                    ("35834", "Keepstar"),
                    ("40340", "Upwell Palatine Keepstar"),
                    ("35835", "Athanor"),
                    ("35836", "Tatara"),
                    ("35825", "Raitaru"),
                    ("35826", "Azbel"),
                    ("35827", "Sotiyo"),
                    ("35841", "Ansiblex Jump Bridge"),
                    ("35840", "Pharolux Cyno Beacon"),
                    ("37534", "Tenebrex Cyno Jammer"),
                    ("4736", "Orbital Skyhook"),
                    ("81826", "Metenox Moon Drill"),
                    ("32458", "Sovereignty Hub"),
                ],
                help_text="Structure type must be one of the selected or leave blank to match any.",
                max_length=118,
            ),
        ),
    ]
