# Generated by Django 4.2.18 on 2025-08-08 11:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("structuretimers", "0006_add_theft_timer_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationrule",
            name="exclude_structure_types",
            field=models.ManyToManyField(
                blank=True,
                help_text="Structure type must NOT be one of the selected",
                related_name="notification_rule_exclude_structure_types",
                to="eveuniverse.evetype",
            ),
        ),
        migrations.AddField(
            model_name="notificationrule",
            name="require_structure_types",
            field=models.ManyToManyField(
                blank=True,
                help_text="Structure type must be one of the selected or leave blank to match any.",
                related_name="+",
                to="eveuniverse.evetype",
            ),
        ),
    ]
