# Generated by Django 4.2.18 on 2025-08-21 14:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("structuretimers", "0007_notificationrule_exclude_structure_types_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="StructureTimersEveType",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("eveuniverse.evetype",),
        ),
    ]
