# Generated by Django 4.2.18 on 2026-04-08 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eve_sde", "0018_blueprintactivity_blueprintactivityproduct_and_more"),
        ("structuretimers", "0008_structuretimersevetype"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationrule",
            name="exclude_regions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Timer must NOT be created within one of the given regions",
                related_name="+",
                to="eve_sde.region",
            ),
        ),
        migrations.AlterField(
            model_name="notificationrule",
            name="exclude_structure_types",
            field=models.ManyToManyField(
                blank=True,
                help_text="Structure type must NOT be one of the selected",
                related_name="notification_rule_exclude_structure_types",
                to="eve_sde.itemtype",
            ),
        ),
        migrations.AlterField(
            model_name="notificationrule",
            name="require_regions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Timer must be created within one of the given regions or leave blank to match any.",
                related_name="+",
                to="eve_sde.region",
            ),
        ),
        migrations.AlterField(
            model_name="notificationrule",
            name="require_structure_types",
            field=models.ManyToManyField(
                blank=True,
                help_text="Structure type must be one of the selected or leave blank to match any.",
                related_name="+",
                to="eve_sde.itemtype",
            ),
        ),
        migrations.AlterField(
            model_name="stagingsystem",
            name="eve_solar_system",
            field=models.OneToOneField(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="+",
                to="eve_sde.solarsystem",
            ),
        ),
        migrations.AlterField(
            model_name="timer",
            name="eve_solar_system",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="eve_sde.solarsystem",
            ),
        ),
        migrations.AlterField(
            model_name="timer",
            name="structure_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="eve_sde.itemtype",
            ),
        ),
    ]
